name: Build CI
on:
  push:
    branches:
      - '**'
jobs:
  build:
    strategy:
      matrix: 
        os: [windows-latest]
        dotnet: [8.0.x]
    
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
      
      - name: Publish win-x64
        run: dotnet publish CMSL.Launcher -c Release -r win-x64 -p:PublishSingleFile=true
        
      - name: Upload win-x64
        uses: actions/upload-artifact@v4
        with:
          name: win-x64
          path: |
            CMSL.Launcher/bin/Release/net8.0/win-x64/publish
      
      - name: Publish win-x86
        run: dotnet publish CMSL.Launcher -c Release -r win-x86 -p:PublishSingleFile=true
      
      - name: Upload win-x86
        uses: actions/upload-artifact@v4
        with:
          name: win-x86
          path: |
            CMSL.Launcher/bin/Release/net8.0/win-x86/publish
      
      - name: Publish win-arm64
        run: dotnet publish CMSL.Launcher -c Release -r win-arm64 -p:PublishSingleFile=true
      
      - name: Upload win-arm64
        uses: actions/upload-artifact@v4
        with:
          name: win-arm64
          path: |
            CMSL.Launcher/bin/Release/net8.0/win-arm64/publish
